baseURL = "https://cb-technologists.github.io/"
languageCode = "en-us"
title = "CloudBees Technologists"
theme = "hello-friend-ng"

googleAnalytics = "UA-141077309-1"
enableAuthor = true

[params]
  dateformNum     = "2006-01-02"

  homeSubtitle = "Continuously Learning, Continuously Teaching"
  gitUrl = "https://github.com/cb-technologists/blog/commit/"

  [[params.social]]
    name = "email"
    url  = "mailto:technologists@cloudbees.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/cb-technologists/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[taxonomies]
  tags = "tags"
  series = "series"
